In [2]:
import pandas as pd
import numpy as np
#reading input data files for ml model training 
train_data = pd.read_excel("PQ_1.xlsx", usecols="B:E",skiprows=100002)
Vdc_1=pd.read_excel("Vdc_1.xlsx", usecols="B:C",skiprows=100002)
Vs_1=pd.read_excel("Vs_1.xlsx", usecols="B:D",skiprows=100002)
Idc_1=pd.read_excel("Idc_1.xlsx", usecols="B:C",skiprows=100002)
Is_1=pd.read_excel("Is_1.xlsx", usecols="B:D",skiprows=100002)
train_data=np.concatenate((train_data, Vdc_1,Vs_1,Idc_1,Is_1), axis=1)
train_data = pd.DataFrame(data=train_data)
print(train_data.shape)
train_data.describe()

(50000, 14)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,-931.875523,899.996451,0.010224,-0.004468,599.981783,594.225500,0.003480,0.001547,-0.005027,-1.535362,-1.530386,0.000114,-0.001364,0.001250
std,2.466219,0.154757,0.174811,0.161377,1.628571,1.666889,218.068474,218.039698,218.023325,0.021992,0.027448,1.425044,1.425668,1.424904
min,-939.392780,899.526106,-0.686010,-0.518044,595.359047,589.881844,-317.155719,-317.174208,-316.946901,-1.626516,-1.650864,-2.040729,-2.042136,-2.036507
25%,-932.674144,899.886207,-0.102493,-0.117979,598.735286,593.014749,-214.204689,-214.404769,-214.474508,-1.549718,-1.547341,-1.425896,-1.428106,-1.424386
50%,-931.783435,899.991315,0.014799,-0.006892,599.994797,594.167872,0.212797,-0.108504,-0.998207,-1.533815,-1.529109,-0.000717,0.000268,0.000341
75%,-931.011394,900.099170,0.128662,0.109586,601.202982,595.453952,214.327320,214.794533,214.342607,-1.519686,-1.511834,1.426188,1.424922,1.427599
max,-921.782518,900.515468,0.604444,0.488796,605.351088,598.615021,316.935574,316.924889,316.981069,-1.468571,-1.441937,2.038365,2.042171,2.044322

In [3]:
#reading outlier data points, outliers correspond to faults 
outlier_data = pd.read_excel("PQ_4.xlsx", usecols="B:E",skiprows=100002)
Vdc_4=pd.read_excel("Vdc_4.xlsx", usecols="B:C",skiprows=100002)
Vs_4=pd.read_excel("Vs_4.xlsx", usecols="B:D",skiprows=100002)
Idc_4=pd.read_excel("Idc_4.xlsx", usecols="B:C",skiprows=100002)
Is_4=pd.read_excel("Is_4.xlsx", usecols="B:D",skiprows=100002)
outlier_data=np.concatenate((outlier_data, Vdc_4,Vs_4,Idc_4,Is_4), axis=1)
outlier_data = pd.DataFrame(data=outlier_data)
print(outlier_data.shape)
outlier_data.describe()

(50000, 14)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,-0.040621,-2.394531,-9.466789,-0.163484,517.990607,517.946602,-0.000189,-0.003975,0.004164,-0.000025,0.004267,-0.000069,-0.001765,0.001834
std,0.112897,0.377157,0.112908,0.457593,0.489655,0.405483,230.319736,230.317741,230.319156,0.000005,0.005531,0.013701,0.013705,0.013697
min,-0.205278,-3.439062,-9.631299,-0.968161,516.529183,516.713063,-325.715280,-325.719085,-325.712496,-0.000031,-0.012950,-0.019475,-0.021218,-0.017578
25%,-0.153426,-2.662766,-9.579648,-0.606432,517.657080,517.613759,-230.305747,-230.090422,-230.057908,-0.000028,0.000201,-0.013771,-0.015469,-0.011863
50%,-0.040563,-2.393745,-9.466822,-0.147647,517.919936,517.932874,-0.000158,-0.004011,0.004169,-0.000026,0.004453,-0.000069,-0.001765,0.001833
75%,0.072228,-2.131181,-9.353977,0.271564,518.374724,518.284778,230.305429,230.082392,230.066289,-0.000021,0.008278,0.013632,0.011940,0.015530
max,0.123907,-1.349398,-9.302103,0.647441,519.239847,519.021783,325.719282,325.711087,325.717931,-0.000016,0.022423,0.019336,0.017689,0.021247

In [4]:
import numpy as np
from sklearn.neighbors import LocalOutlierFactor

In [5]:
LOF= LocalOutlierFactor(n_neighbors=20, novelty=True, contamination=0.01)
LOF.fit(train_data)

LocalOutlierFactor(algorithm='auto', contamination=0.01, leaf_size=30,
                   metric='minkowski', metric_params=None, n_jobs=None,
                   n_neighbors=20, novelty=True, p=2)

In [6]:
y_pred_train=LOF.predict(train_data)
y_pred_outliers=LOF.predict(outlier_data)
n_error_train=y_pred_train[y_pred_train==-1].size
print('train accuracy:',100-n_error_train/50000*100)
n_accuracy_outliers=y_pred_outliers[y_pred_outliers==-1].size
print('outlier prediction accuracy:' ,n_accuracy_outliers/50000*100)

train accuracy: 99.29
outlier prediction accuracy: 100.0

In [11]:
from sklearn.covariance import EllipticEnvelope
EC=EllipticEnvelope(support_fraction=1.,contamination=0.261)
EC.fit(train_data)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/covariance/robust_covariance.py:644: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn("The covariance matrix associated to your dataset "

EllipticEnvelope(assume_centered=False, contamination=0.261, random_state=None,
                 store_precision=True, support_fraction=1.0)

In [12]:
y_pred_train=EC.predict(train_data)
y_pred_outliers=EC.predict(outlier_data)
n_error_train=y_pred_train[y_pred_train==-1].size
print('train accuracy:',100-n_error_train/50000*100)
n_accuracy_outliers=y_pred_outliers[y_pred_outliers==-1].size
print('outlier prediction accuracy:' ,n_accuracy_outliers/50000*100)

train accuracy: 73.9
outlier prediction accuracy: 100.0